---
# See documentation: https://packit.dev/docs/configuration/

specfile_path: python-rtslib.spec

upstream_package_name: rtslib-fb
downstream_package_name: python-rtslib

upstream_tag_template: v{version}

actions:
  create-archive:
    - hatch build -t sdist
    - bash -c "ls -1t ./dist/*.tar.gz | head -n 1"

srpm_build_deps:
  - python3-devel
  - hatch
  - python3-hatchling
  - python3-hatch-vcs

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-latest-stable
      - epel-10

  - job: tests
    trigger: pull_request
    targets:
      - fedora-latest-stable
      - epel-10
